"""Predictive ML endpoints.

Separate from RAG on purpose: these do not involve retrieval or a language
model, and they must keep working when the LLM is unavailable.
"""

from __future__ import annotations

from dataclasses import asdict

from fastapi import APIRouter

from ..core.errors import ERROR_RESPONSES
from ..ml.predictor import RISK_BAND_DESCRIPTION
from ..schemas.ml import (
    BatchDelayPredictionRequest,
    BatchDelayPredictionResponse,
    DelayPredictionRequest,
    DelayPredictionResponse,
    ModelInfoResponse,
)
from .deps import DelayPredictorDep

router = APIRouter(prefix="/ml", tags=["ML"], responses=ERROR_RESPONSES)

_SYNTHETIC_NOTE = (
    "\n\n> The model is trained on **synthetic** data generated by "
    "`app.ml.dataset`. It demonstrates a working prediction pipeline; it is "
    "not a validated operational tool."
)


@router.post(
    "/predict-delay",
    response_model=DelayPredictionResponse,
    summary="Predict whether a report will miss its turnaround target",
    description=(
        "Returns the probability that a request misses its target turnaround, "
        f"banded as **{RISK_BAND_DESCRIPTION}**.\n\n"
        "Only `test_type` is required. Anything omitted is inferred from the "
        "branch and test profiles the model was trained on, and every inferred "
        "value is returned in `inferred_fields` so the caller can see which "
        "numbers were theirs.\n\n"
        "Returns **503** when no model artifact exists -- run "
        "`python -m app.ml.train`." + _SYNTHETIC_NOTE
    ),
)
def predict_delay(
    payload: DelayPredictionRequest, predictor: DelayPredictorDep
) -> DelayPredictionResponse:
    prediction = predictor.predict(payload.model_dump(exclude_none=True))
    return DelayPredictionResponse(**asdict(prediction))


@router.post(
    "/predict-delay/batch",
    response_model=BatchDelayPredictionResponse,
    summary="Score many requests in one call",
    description=(
        "Same model and bands as the single endpoint, evaluated in one pass. "
        "Used by the operations dashboard, which would otherwise make one "
        "round trip per report." + _SYNTHETIC_NOTE
    ),
)
def predict_delay_batch(
    payload: BatchDelayPredictionRequest, predictor: DelayPredictorDep
) -> BatchDelayPredictionResponse:
    predictions = predictor.predict_many(
        [item.model_dump(exclude_none=True) for item in payload.items]
    )
    return BatchDelayPredictionResponse(
        predictions=[DelayPredictionResponse(**asdict(item)) for item in predictions],
        model_version=predictions[0].model_version if predictions else "",
        count=len(predictions),
    )


@router.get(
    "/model",
    response_model=ModelInfoResponse,
    summary="Metadata for the served model",
    description=(
        "Version, algorithm, training data, feature schema and the metrics "
        "measured on the held-out test split, plus every candidate considered "
        "during selection." + _SYNTHETIC_NOTE
    ),
)
def model_info(predictor: DelayPredictorDep) -> ModelInfoResponse:
    metadata = predictor.metadata
    return ModelInfoResponse(
        model_name=metadata.model_name,
        version=metadata.version,
        algorithm=metadata.algorithm,
        trained_at=metadata.trained_at,
        synthetic_data=metadata.synthetic_data,
        dataset=metadata.dataset,
        feature_schema=metadata.feature_schema,
        metrics=metadata.metrics,
        candidates=metadata.candidates,
        selection_metric=metadata.selection_metric,
        notes=metadata.notes,
    )
