"""add login lockout fields

Revision ID: 202608290001
Revises: 202608280002
Create Date: 2026-08-29 11:23:59.170793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "202608290001"
down_revision: Union[str, None] = '202608280002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###
